"""empty message

Revision ID: 209d9e1d79bc
Revises: 
Create Date: 2019-11-20 15:41:52.118148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209d9e1d79bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_status')
    # ### end Alembic commands ###
