"""empty message

Revision ID: 5b43cb248af7
Revises: 209d9e1d79bc
Create Date: 2019-11-20 15:47:54.377994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b43cb248af7'
down_revision = '209d9e1d79bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_status', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_status', 'name')
    # ### end Alembic commands ###
