"""empty message

Revision ID: dee2a86d2710
Revises: 2daf676f1564
Create Date: 2019-12-01 17:42:02.056683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee2a86d2710'
down_revision = '2daf676f1564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_status', sa.Column('temp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_status', 'temp')
    # ### end Alembic commands ###
